# RAG Content Retriever Configuration
# -----------------------------------
# This file contains configuration settings for the RAG Content Retriever.
# For security, API keys should be provided via environment variables rather
# than in this configuration file.

# Jina AI Configuration
jina:
  # Your Jina AI API key (recommended: use JINA_API_KEY environment variable instead)
  api_key: "jina_6849074af6344a89985255e94211d8a02mGWOS6fhgfiz5x7SFbIEd_jIXMZ"
  # Embedding model to use
  embedding_model: "jina-embeddings-v3"
  # Reranker model to use
  reranker_model: "jina-reranker-v2-base-multilingual"

# Google Gemini Configuration
gemini:
  # Your Gemini API key (recommended: use GEMINI_API_KEY environment variable instead)
  api_key: "AIzaSyAvre2O31doywSHTzwOMDGW6-SL2yO9-No"
  # Gemini model to use
  model: "gemini-2.0-flash-001"

# Qdrant Vector Database Configuration
qdrant:
  # Qdrant server URL (if running locally, use "localhost")
  url: "135.181.129.60"
  # Qdrant server port
  port: 6333
  # Name of the collection to use
  collection_name: "content_library"

# Chunking Configuration
chunking:
  # Maximum tokens per chunk (based on research findings)
  max_chunk_tokens: 1000
  # Number of tokens to overlap between chunks
  overlap_tokens: 100

# Embedding Process Configuration
embedding:
  # Number of chunks to embed in each batch
  batch_size: 100
  # Directory to store checkpoint files for resumable processing
  checkpoint_dir: "embedding_checkpoints"

# Retrieval Configuration
retrieval:
  # Maximum tokens in consolidated chunks
  max_consolidated_tokens: 4000
  # Default number of results to return from search
  default_result_limit: 20

# Logging Configuration
logging:
  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # Main log file path
  file: "rag_retriever.log"
  # Embedding process log file
  embedding_log: "embedding_process.log"