version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./embedding_checkpoints:/app/embedding_checkpoints
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - QDRANT_URL=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - rag-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge