services:
  api:
    build: .
    ports:
      - "8333:8000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./embedding_checkpoints:/app/embedding_checkpoints
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - QDRANT_URL=qdrant
      - QDRANT_PORT=6333
      - EMBEDDING_JINA_MODEL=jina-embeddings-v3
      - EMBEDDING_OPENAI_MODEL=text-embedding-3-small
      - EXPANSION_GEMINI_MODEL=gemini-1.5-flash
      - EXPANSION_OPENAI_MODEL=gpt-4.1-nano
      - DEFAULT_EMBEDDING_PROVIDER=jina
      - DEFAULT_EXPANSION_PROVIDER=openai
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - rag-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge